version: 0.2

phases:
  pre_build:
    commands:
      - echo Pre_build Phase
      - yarn install
  build:
    commands:
      - echo Build Phase
      - yarn run build
  post_build:
    commands:
      - echo PostBuild Phase
      - aws s3 sync build/ s3://for-demo-vuejs-app
      - aws cloudfront create-invalidation --distribution-id E2MPJE9VKZ5MP8 --paths "/*";
